Enhancing File Control
dbm-network/mods pull request #576
Opened 2020-09-14 08:10 UTC by infinitytmbots

**Please describe the changes this PR makes and why it should be merged:**
The old pull request had to be closed due an error popped by the repository. Added the visibility factor.
**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-09-14 11:28 UTC, almeidx requested changes

2020-09-14 11:28 UTC, almeidx commented on actions/file_control_MOD.js
> +    this.fields = ['input', 'format', 'filename', 'filepath', 'filetask', 'input2', 'togglestatus']
why didn't you just add it to the line above?

2020-09-14 11:28 UTC, almeidx commented on actions/file_control_MOD.js
> -
add this back

2020-10-05 20:36 UTC, DetroitWhiskey136 requested changes
fix eslint errors/warnings please

2020-10-07 09:18 UTC, infinitytmbots commented
okay

2020-10-07 10:46 UTC, DetroitWhiskey136 approved these changes
lgtm

2020-10-07 10:46 UTC, merged