Add delete invite action
dbm-network/mods pull request #618
Opened 2020-12-17 21:19 UTC by marceaupatu123

**Delete Invite**

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-12-20 14:07 UTC, DetroitWhiskey136 commented on package.json
> +    "eslint-config-standard-jsx": "^10.0.0",
This is almost certainly not needed

2020-12-20 14:07 UTC, DetroitWhiskey136 commented on package.json
> +    "eslint-plugin-react": "^7.21.5",
This is almost certainly not needed

2020-12-20 14:36 UTC, marceaupatu123 commented on package.json
> +    "eslint-config-standard-jsx": "^10.0.0",
Fixed

2020-12-20 14:36 UTC, marceaupatu123 commented on package.json
> +    "eslint-plugin-react": "^7.21.5",
Fixed

2020-12-21 12:37 UTC, almeidx requested changes

2020-12-21 12:37 UTC, almeidx commented on actions/delete_invite.js
> +    if (type !== varType) return
```suggestion
    if (parseInt(data.storage) !== varType) return
```

2020-12-21 12:37 UTC, almeidx commented on actions/delete_invite.js
> +      .then(async (invite) => {
Any reason for this to be async?

2020-12-21 13:02 UTC, marceaupatu123 commented on actions/delete_invite.js
> +      .then(async (invite) => {
Changed.

2020-12-21 16:22 UTC, almeidx approved these changes

2020-12-21 17:09 UTC, DetroitWhiskey136 approved these changes

2020-12-21 17:09 UTC, merged