Create embed enhancement
dbm-network/mods pull request #622
Opened 2020-12-26 13:14 UTC by Michael55555

**Please describe the changes this PR makes and why it should be merged:**
The changes in this PR include an enhancement to the "Create Embed Message" mod, that you can already add the embed description in this action, instead of having to add a separate action to it.

**Status**

- [] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [x] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-12-26 13:26 UTC, almeidx requested changes
Unnecessary. This would defeat the purpose of the `Set Embed Description` action.

2020-12-26 13:37 UTC, Michael55555 commented
> Unnecessary. This would defeat the purpose of the `Set Embed Description` action.

Kind of, but most people would be happy is their action lists would be a bit shorter. Sometimes they can get really long. I am sure that people would use `Set Embed Description` in case they have to do it separately for their specific use case.

2020-12-26 14:05 UTC, DetroitWhiskey136 commented on actions/create_embed_message.js
> -  fields: ['title', 'author', 'color', 'url', 'authorIcon', 'authorUrl', 'imageUrl', 'thumbUrl', 'timestamp', 'debug', 'timestamp1', 'timestamp2', 'text', 'year', 'month', 'day', 'hour', 'minute', 's
undo this change please

2020-12-26 14:05 UTC, DetroitWhiskey136 commented on actions/create_embed_message.js
> +          authorUrl.placeholder = 'Unavailable!'
lol glad someone fixed that

2020-12-26 14:05 UTC, DetroitWhiskey136 commented on actions/create_embed_message.js
> -        embed.setAuthor(this.evalMessage(data.author, cache), this.evalMessage(data.authorIcon, cache), this.evalMessage(data.authorUrl, cache))
adding new lines just grows the file size try to minimize that.

2020-12-26 14:05 UTC, DetroitWhiskey136 commented on actions/create_embed_message.js
> -        embed.setAuthor(this.evalMessage(data.author, cache), this.evalMessage(data.authorIcon, cache))
and here

2020-12-26 14:05 UTC, DetroitWhiskey136 commented on actions/create_embed_message.js
> -          embed.setTimestamp(new Date(year || null, month || null, day || null, hour || null, minute || null, second || null))
and here

2020-12-26 14:05 UTC, DetroitWhiskey136 commented on actions/create_embed_message.js
> -            console.log('Invaild UTC timestamp! Changed from [String Timestamp] to [Current Timestamp].')
same here

2020-12-26 14:06 UTC, DetroitWhiskey136 commented on actions/create_embed_message.js
> -  fields: ['title', 'author', 'color', 'url', 'authorIcon', 'authorUrl', 'imageUrl', 'thumbUrl', 'timestamp', 'debug', 'timestamp1', 'timestamp2', 'text', 'year', 'month', 'day', 'hour', 'minute', 's
if the line length is to long just split it into two lines

2020-12-26 14:29 UTC, DetroitWhiskey136 approved these changes
LGTM

2020-12-26 15:07 UTC, DetroitWhiskey136 commented
Almeida made a good point, what if people want to set the description but not create a new embed each time, like when your edit an embed, this would be probably with this change

2020-12-26 18:39 UTC, Michael55555 commented
Yes, this is indeed a good point! But that's also the reason for not deleting the "set embed description" action, so that people still have the same options. Anyways, it would be great to make people edit their embeds with edit embed. We can release options from time to time that make this shift happen to the point where people create embeds with "Create Embed Message" and edit them with "Edit Embed Message".

2020-12-27 02:30 UTC, almeidx commented
If we're going to add the description part to Create Embed Message, we might as well add Fields and Footer support

2020-12-27 09:31 UTC, Michael55555 commented
I'm working on that at the moment

2021-01-09 13:25 UTC, Michael55555 commented
Unfortunately I don't have time to add the fields atm. I would be glad if someone else takes this over.

2021-01-31 23:26 UTC, Michael55555 commented
> Unnecessary. This would defeat the purpose of the `Set Embed Description` action.

Alright agreed

2021-01-31 23:26 UTC, closed without merging