this is still a heavy wip, but needed for testing because of how the mod works
dbm-network/mods pull request #661
Opened 2021-04-24 10:11 UTC by DetroitWhiskey136

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-04-24 10:16 UTC, DetroitWhiskey136 commented
I'll work on eslint errors while I wait

2021-04-25 09:42 UTC, almeidx requested changes

2021-04-25 09:42 UTC, almeidx commented on extensions/dbm_dashboard/dashboard_EXT.js
> +          fs.mkdirSync(require('path').join(__dirname, 'dashboard_EXT'))
```suggestion
        if (!fs.existsSync(path.join(__dirname, 'dashboard_EXT'))) {
          fs.mkdirSync(path.join(__dirname, 'dashboard_EXT'))
```

2021-04-25 09:42 UTC, almeidx commented on extensions/dbm_dashboard/dashboard_EXT.js
> +          fs.mkdirSync(require('path').join(__dirname, 'dashboard_EXT'))
```suggestion
        if (!fs.existsSync(path.join(__dirname, 'dashboard_EXT'))) {
          fs.mkdirSync(path.join(__dirname, 'dashboard_EXT'))
```

2021-04-25 09:42 UTC, almeidx commented on extensions/dbm_dashboard/dashboard_EXT.js
> +          fs.mkdirSync(require('path').join(__dirname, 'dashboard_EXT'))
```suggestion
        if (!fs.existsSync(path.join(__dirname, 'dashboard_EXT'))) {
          fs.mkdirSync(path.join(__dirname, 'dashboard_EXT'))
```

2021-04-25 09:51 UTC, merged