Fix & Merge #628 + Help Avoid Confusion
dbm-network/mods pull request #666
Opened 2021-05-18 00:14 UTC by Fisheiyy

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [x] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [x] This PR changes DBM's interface (methods or parameters added to default methods)
- [] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-05-19 18:19 UTC, DetroitWhiskey136 commented
Please fix all linting errors and provide a descriptive overview of these changes and what they provide to the mod pack

2021-05-20 03:34 UTC, DetroitWhiskey136 commented
a Category is called a Category Channel have a problem with that take it up with discord

2021-05-20 03:34 UTC, Fisheiyy commented
> a Category is called a Category Channel have a problem with that take it up with discord

it causes a lot of confusion though

2021-05-27 02:41 UTC, DetroitWhiskey136 requested changes

2021-05-27 02:41 UTC, DetroitWhiskey136 commented on actions/create_category_MOD.js
> +  name: 'Create Category',
use the displayName property instead of changing the mods name, the method you used will broke all previous Rawdata

2021-05-27 02:55 UTC, DanTheComputerMan commented
Calling this "Create Category" instead of "Create Category Channel" will create more confusion than leaving it as is. This will bring up what kind of category is being created? Is it Command category, Channel category, Event Category, or some other kind of category?

This is a Category Channel and should be described as such.

2021-05-27 02:58 UTC, TheMonDon commented
It seems fine as long as you revert the change to category channels

2021-05-27 04:20 UTC, TheMonDon approved these changes

2021-05-27 04:21 UTC, DetroitWhiskey136 approved these changes

2021-05-27 04:21 UTC, merged