Fix - Join/Leave Voice Event avoids Stage Channels
dbm-network/mods pull request #686
Opened 2021-05-30 04:47 UTC by Lucasamiel0406

**Please describe the changes this PR makes and why it should be merged:**
> A fix for Stage Channels crashing bots due to being `null` to Discord.JS, several people have been complaining about it a good time ago and even in nowadays.
Tested several times the event against false triggers or not triggering properly for voice channels and works fine.

**Status**

- [X] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-05-30 04:58 UTC, TheMonDon commented
You're going to have to remove the semicolons before you can get this approved, alms linting thing hates semicolons.

I'll get danno or alm to start the eslint check when they're awake

2021-05-31 06:48 UTC, TheMonDon approved these changes

2021-05-31 23:01 UTC, almeidx requested changes

2021-05-31 23:01 UTC, almeidx commented on events/member_join_voice_channel_EVT.js
> +      if (newChannel == null || !(!oldChannel && newChannel)) return
```suggestion
      if (oldChannel || !newChannel) return

```

2021-05-31 23:01 UTC, almeidx commented on events/member_leave_voice_channel_EVT.js
> +      if (oldChannel == null || !(oldChannel && !newChannel)) return
```suggestion
      if (!oldChannel || newChannel)) return

```

2021-06-01 23:22 UTC, almeidx requested changes

2021-06-01 23:22 UTC, almeidx commented on events/member_join_voice_channel_EVT.js
>        const server = (oldChannel || newChannel).guild
```suggestion
      const server = newChannel.guild

```

2021-06-01 23:22 UTC, almeidx commented on events/member_leave_voice_channel_EVT.js
>        const server = (oldChannel || newChannel).guild
```suggestion
      const server = oldChannel.guild

```

2021-06-01 23:24 UTC, almeidx commented on events/member_leave_voice_channel_EVT.js
> +      if (!oldChannel || newChannel)) return
```suggestion
      if (!oldChannel || newChannel) return

```

2021-06-03 15:11 UTC, almeidx approved these changes

2021-06-03 15:12 UTC, merged