Create store_user_info_MOD.js
dbm-network/mods pull request #703
Opened 2021-06-18 01:14 UTC by TheMonDon

**Please describe the changes this PR makes and why it should be merged:**
Store Member Info does not work right with users, so I made a user info mod.

**Status**

- [X] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [X] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-06-24 00:35 UTC, almeidx reviewed
I disagree with this change. I would rather you fix the Store Member Info action to work with users instead of creating a Store User Info separately

2021-06-24 05:31 UTC, TheMonDon commented
> I disagree with this change. I would rather you fix the Store Member Info action to work with users instead of creating a Store User Info separately

I think you are wrong as they're two different things they should be kept separate rather than make store member info also have user class

2021-06-24 05:31 UTC, TheMonDon commented
> I disagree with this change. I would rather you fix the Store Member Info action to work with users instead of creating a Store User Info separately

I think you are wrong as they're two different things they should be kept separate rather than make store member info also have user class

2021-06-27 18:59 UTC, almeidx requested changes

2021-06-27 18:59 UTC, almeidx commented on actions/store_user_info_MOD.js
> +  </div>`
Use 2 spaces of indentation, and start at 0 (and fix the weird indentation on the select#options)

2021-06-27 18:59 UTC, almeidx commented on actions/store_user_info_MOD.js
> +    const dataType = data.info[info]
This doesn't make much sense, does it?

2021-06-27 18:59 UTC, almeidx commented on actions/store_user_info_MOD.js
> +    if (type !== varType) return
```suggestion
    if (parseInt(data.storage) !== varType) return
```

2021-06-27 18:59 UTC, almeidx commented on actions/store_user_info_MOD.js
> +    let user = this.getMember(dUser, varName, cache)
```suggestion
    const userType = parseInt(data.user)
    const varName = this.evalMessage(data.varName, cache)
    const info = parseInt(data.info)
    let user = this.getMember(userType, varName, cache)
```

2021-06-27 18:59 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        result = this.dest(user, 'discriminator')
```suggestion
        result = user.discriminator
```

2021-06-27 18:59 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        result = this.dest(user, 'tag')
```suggestion
        result = user.tag
```

2021-06-27 18:59 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        result = this.dest(user, 'createdAt')
```suggestion
        result = user.createdAt
```

2021-06-27 18:59 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        result = this.dest(user, 'createdTimestamp')
```suggestion
        result = user.createdTimestamp
```

2021-06-27 18:59 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        const flags = this.dest(user, 'flags')
```suggestion
        const flags = user.flags
```

2021-06-27 20:46 UTC, almeidx requested changes

2021-06-27 20:46 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        dataType = 'Text'
It's a list. Just merge it with case 13

2021-06-27 21:41 UTC, almeidx approved these changes

2021-06-27 21:51 UTC, merged