Small Fix
dbm-network/mods pull request #709
Opened 2021-06-26 03:58 UTC by TheMonDon

**Please describe the changes this PR makes and why it should be merged:**
the .catch which I uh, didn't catch, threw an error for some people.
**Status**

- [X] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [X] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-06-26 18:40 UTC, almeidx requested changes
I would like if you addressed these issues as well:

- [ ] `fs.writeFileSync` does not take a callback
https://github.com/dbm-network/mods/blob/a08bbcba8a0900e7f3e7cacb438bf0848c332eda/actions/file_control_MOD.js#L232
https://github.com/dbm-network/mods/blob/a08bbcba8a0900e7f3e7cacb438bf0848c332eda/actions/file_control_MOD.js#L239
https://github.com/dbm-network/mods/blob/a08bbcba8a0900e7f3e7cacb438bf0848c332eda/actions/file_control_MOD.js#L243

- [ ] `fs.appendFileSync` does not take a callback
https://github.com/dbm-network/mods/blob/a08bbcba8a0900e7f3e7cacb438bf0848c332eda/actions/file_control_MOD.js#L251
https://github.com/dbm-network/mods/blob/a08bbcba8a0900e7f3e7cacb438bf0848c332eda/actions/file_control_MOD.js#L255

- [ ] Use `fs.unlinkSync` instead
https://github.com/dbm-network/mods/blob/a08bbcba8a0900e7f3e7cacb438bf0848c332eda/actions/file_control_MOD.js#L267

- [ ] Use `fs.copySync` instead
https://github.com/dbm-network/mods/blob/a08bbcba8a0900e7f3e7cacb438bf0848c332eda/actions/file_control_MOD.js#L273

2021-06-27 20:52 UTC, almeidx commented on actions/file_control_MOD.js
> +          // return console.error(`${lmg} copying: [${err}]`)
```suggestion
```

2021-06-27 20:52 UTC, almeidx commented on actions/file_control_MOD.js
> +    } = this
Revert

2021-06-27 22:02 UTC, DetroitWhiskey136 approved these changes

2021-06-27 23:24 UTC, almeidx requested changes

2021-06-27 23:24 UTC, almeidx commented on actions/file_control_MOD.js
> +          }
```suggestion
          fs.writeFileSync(fpath, togglestat === 'yes' ? JSON.stringify(itext) : itext)
```

2021-06-27 23:24 UTC, almeidx commented on actions/file_control_MOD.js
> +          }
```suggestion
          fs.appendFileSync(fpath, `${togglestat === 'yes' ? JSON.stringify(itext) : itext}\r\n`)
```

2021-06-28 00:02 UTC, almeidx approved these changes

2021-06-28 00:02 UTC, merged