Add options for strict conversion in Convert Variable
dbm-network/mods pull request #718
Opened 2021-06-27 08:43 UTC by tlfn

**Please describe the changes this PR makes and why it should be merged:**
It add the options not parsing the Number, but converting to Number (Int/Float)

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [x] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [x] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-06-27 22:07 UTC, TheMonDon approved these changes

2021-06-28 10:27 UTC, almeidx commented on actions/convert_variable_MOD.js
>      const prse2 = parseInt(data.conversion)
```suggestion
```

2021-06-28 10:27 UTC, almeidx commented on actions/convert_variable_MOD.js
>      if (type !== varType) return
```suggestion
    if (parseInt(data.storage2) !== varType) return
```

2021-06-28 10:27 UTC, almeidx commented on actions/convert_variable_MOD.js
>      return ([data.varName2, info2[prse2]])
```suggestion
    return ([data.varName2, info2[parseInt(data.conversion)]])
```

2021-06-28 10:29 UTC, almeidx requested changes

2021-06-28 10:29 UTC, almeidx commented on actions/convert_variable_MOD.js
>      const prse2 = parseInt(data.conversion)
```suggestion
```

2021-06-28 10:29 UTC, almeidx commented on actions/convert_variable_MOD.js
>      return ([data.varName2, info2[prse2]])
```suggestion
    if (parseInt(data.storage2) !== varType) return
    return ([data.varName2, info2[parseInt(data.conversion)]])
```

2021-06-28 10:32 UTC, almeidx approved these changes

2021-06-28 10:32 UTC, merged