Migrate the version to Node v14
dbm-network/mods pull request #725
Opened 2021-06-28 14:52 UTC by tlfn

**Please describe the changes this PR makes and why it should be merged:**
By using Node v14, we can use new features such as Optional chaining, Nullish Coalescing, ...
And using those features make the code more readable, and cleaner.

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-06-29 08:33 UTC, Fisheiyy commented
have you tested anything? also im not sure if its possible to migrate to a newer version of node without having DBM itself be updated to a newer version of node

2021-06-29 22:07 UTC, TheMonDon commented
> have you tested anything? also im not sure if its possible to migrate to a newer version of node without having DBM itself be updated to a newer version of node

It's a draft PR, this will be merged after DBM update and discord.js v13 comes out. Not tested yet just preliminary code.

2021-06-29 22:44 UTC, almeidx requested changes

2021-06-29 22:44 UTC, almeidx commented on actions/check_if_member_MOD.js
> +        result = member.voice?.speaking ?? false
```suggestion
        result = !!member.voice?.speaking
```

2021-06-29 22:44 UTC, almeidx commented on actions/check_if_member_MOD.js
> +        result = member.voice?.channel ?? false
```suggestion
        result = !!member.voice?.channel
```

2021-06-29 22:44 UTC, almeidx commented on actions/check_if_member_MOD.js
> +        result = member.voice?.mute ?? false
```suggestion
        result = !!member.voice?.mute
```

2021-06-29 22:44 UTC, almeidx commented on actions/check_if_member_MOD.js
> +        result = member.voice?.deaf ?? false
```suggestion
        result = !!member.voice?.deaf
```

2021-06-29 22:44 UTC, almeidx commented on actions/check_if_member_has_role_MOD.js
> +        result = member.every((mem) => mem?.roles?.cache?.has?.(role.id) === true)
```suggestion
        result = member.every((mem) => mem?.roles?.cache.has(role.id))
```

2021-06-29 22:44 UTC, almeidx commented on actions/check_if_member_has_role_MOD.js
> +        result = member?.roles?.cache?.has?.(role.id) === true
```suggestion
        result = !!member?.roles?.cache.has(role.id)
```

2021-06-29 22:44 UTC, almeidx commented on actions/check_if_user_reacted_MOD.js
> +      result = member.every((user) => reaction?.users?.cache?.has?.(user.id) === true)
```suggestion
      result = member.every((user) => reaction?.users?.cache.has(user.id))
```

2021-06-29 22:44 UTC, almeidx commented on actions/check_if_user_reacted_MOD.js
> +      result = reaction?.users?.cache?.has?.(member.id) === true
```suggestion
      result = !!reaction?.users?.cache.has(member.id)
```

2021-06-29 22:44 UTC, almeidx commented on actions/control_permissons_MOD.js
> +        if (!permissions.allow?.has?.(perms) !== true) {
```suggestion
        if (!permissions.allow?.has(perms)) {
```

2021-06-29 22:44 UTC, almeidx commented on actions/control_permissons_MOD.js
> +        if (permissions.disallow?.has?.(perms) === true) permissions.disallow.remove(perms)
```suggestion
        if (permissions.disallow?.has(perms)) permissions.disallow.remove(perms)
```

2021-06-29 22:44 UTC, almeidx commented on actions/control_permissons_MOD.js
> +        if (permissions.inherit?.includes?.(perms) === true) permissions.inherit.splice(permissions.inherit.indexOf(perms), 1)
```suggestion
        if (permissions.inherit?.includes(perms)) permissions.inherit.splice(permissions.inherit.indexOf(perms), 1)
```

2021-06-29 22:44 UTC, almeidx commented on actions/control_permissons_MOD.js
> +        if (permissions.disallow?.has?.(perms) !== true) {
```suggestion
        if (!permissions.disallow?.has(perms)) {
```

2021-06-29 22:44 UTC, almeidx commented on actions/control_permissons_MOD.js
> +        if (permissions.allow?.has?.(perms) === true) permissions.allow.remove(perms)
```suggestion
        if (permissions.allow?.has(perms)) permissions.allow.remove(perms)
```

2021-06-29 22:44 UTC, almeidx commented on actions/control_permissons_MOD.js
> +        if (permissions.inherit?.includes?.(perms) === true) permissions.inherit.splice(permissions.inherit.indexOf(perms), 1)
```suggestion
        if (permissions.inherit?.includes(perms)) permissions.inherit.splice(permissions.inherit.indexOf(perms), 1)
```

2021-06-29 22:44 UTC, almeidx commented on actions/control_permissons_MOD.js
> +        if (permissions.inherit?.has?.(perms) !== true) {
```suggestion
        if (!permissions.inherit?.has(perms)) {
```

2021-06-29 22:44 UTC, almeidx commented on actions/control_permissons_MOD.js
> +        if (permissions.disallow?.has?.(perms) === true) permissions.disallow.remove(perms)
```suggestion
        if (permissions.disallow?.has(perms)) permissions.disallow.remove(perms)
```

2021-06-29 22:44 UTC, almeidx commented on actions/control_permissons_MOD.js
> +        if (permissions.allow?.has?.(perms) === true) permissions.allow.remove(perms)
```suggestion
        if (permissions.allow?.has(perms)) permissions.allow.remove(perms)
```

2021-06-29 22:44 UTC, almeidx commented on actions/create_animated_emoji_MOD.js
> +    if (server?.emojis?.create === undefined) return this.callnextAction(cache)
```suggestion
    if (!server) return this.callNextAction(cache)
```

2021-06-29 22:44 UTC, almeidx commented on actions/create_category_MOD.js
> +    if (server?.channels?.create === undefined) return this.callnextAction(cache)
```suggestion
    if (!server) return this.callNextAction(cache)
```

2021-06-29 22:44 UTC, almeidx commented on actions/delete_bulk_messages_MOD.js
> +    return `Delete ${data.count} messages from ${channels[parseInt(data.channel)] ?? 'Nothing'}`
```suggestion
    return `Delete ${data.count} messages from ${channels[parseInt(data.channel)] ?? 'nowhere'}`
```

2021-06-29 22:44 UTC, almeidx commented on actions/delete_bulk_messages_MOD.js
> +    } = this
```suggestion
    const { glob, document } = this
```

2021-06-29 22:44 UTC, almeidx commented on actions/delete_bulk_messages_MOD.js
> +    if (source?.messages?.fetch === undefined) return this.callNextAction(cache)
```suggestion
    if (!source) return this.callNextAction(cache)

```

2021-06-29 22:44 UTC, almeidx commented on actions/delete_bulk_messages_MOD.js
> +          })
```suggestion
          filtered = (filtered ?? messages).filter(() => {
            try {
              return !!eval(Con4)
            } catch {
              return false
            }
          })
```

2021-06-29 22:44 UTC, almeidx commented on actions/delete_bulk_messages_MOD.js
> +        let result = deleted.array ? deleted.array() : deleted
```suggestion
        let result = Array.isArray(deleted) ? deleted : deleted.array()
```

2021-06-29 22:44 UTC, almeidx commented on actions/delete_bulk_messages_MOD.js
> +  }
```suggestion
  mod () {}
```

2021-06-29 22:44 UTC, almeidx commented on actions/find_category_MOD.js
> +    if (server?.channels === undefined) return this.callNextAction(cache)
```suggestion
    if (!server) return this.callNextAction(cache)
```

2021-06-29 22:44 UTC, almeidx commented on actions/find_member.js
> +    if (server?.members === undefined) return this.callNextAction(cache)
```suggestion
    if (!server) return this.callNextAction(cache)
```

2021-06-29 22:44 UTC, almeidx commented on actions/remove_message_reactions_MOD.js
> +        ?.catch?.(this.displayError.bind(this, data, cache))
```suggestion
      message?.reactions.removeAll()
        .then(() => this.callNextAction(cache))
        .catch(this.displayError.bind(this, data, cache))
```

2021-06-29 22:44 UTC, almeidx commented on actions/store_game_info_MOD.js
> +    if (mem.presence?.activities?.[0] === undefined) return this.callNextAction(cache)
```suggestion
    if (!mem?.presence?.activities[0]) return this.callNextAction(cache)
```

2021-06-29 22:44 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        result = user.presence?.activities?.filter?.((s) => s?.type !== 'CUSTOM_STATUS')
```suggestion
        result = user.presence?.activities.filter((s) => s.type !== 'CUSTOM_STATUS')
```

2021-06-29 22:44 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        result = user.presence?.activities?.filter?.((s) => s?.type === 'CUSTOM_STATUS')
```suggestion
        result = user.presence?.activities.filter((s) => s.type === 'CUSTOM_STATUS')
```

2021-06-29 22:44 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        result = Object.keys(status ?? {})
```suggestion
        result = Object.keys(user.presence?.clientStatus ?? {})
```

2021-06-29 23:34 UTC, tlfn commented on actions/store_user_info_MOD.js
> +        result = user.presence?.activities?.filter?.((s) => s?.type === 'CUSTOM_STATUS')
This may cause an issue

2021-06-29 23:34 UTC, tlfn commented on actions/store_user_info_MOD.js
> +        result = user.presence?.activities?.filter?.((s) => s?.type !== 'CUSTOM_STATUS')
So does this

2021-06-29 23:34 UTC, tlfn commented on actions/store_game_info_MOD.js
> +    if (mem.presence?.activities?.[0] === undefined) return this.callNextAction(cache)
So does this

2021-06-29 23:35 UTC, tlfn commented on actions/remove_message_reactions_MOD.js
> +        ?.catch?.(this.displayError.bind(this, data, cache))
so does this

2021-06-29 23:37 UTC, tlfn commented on actions/control_permissons_MOD.js
> +        if (permissions.allow?.has?.(perms) === true) permissions.allow.remove(perms)
so does this

2021-06-29 23:37 UTC, tlfn commented on actions/control_permissons_MOD.js
> +        if (permissions.disallow?.has?.(perms) === true) permissions.disallow.remove(perms)
so does this

2021-06-29 23:37 UTC, tlfn commented on actions/control_permissons_MOD.js
> +        if (permissions.inherit?.has?.(perms) !== true) {
so does this

2021-06-29 23:37 UTC, tlfn commented on actions/control_permissons_MOD.js
> +        if (permissions.inherit?.includes?.(perms) === true) permissions.inherit.splice(permissions.inherit.indexOf(perms), 1)
so does this

2021-06-29 23:38 UTC, tlfn commented on actions/control_permissons_MOD.js
> +        if (permissions.allow?.has?.(perms) === true) permissions.allow.remove(perms)
so does this

2021-06-29 23:38 UTC, tlfn commented on actions/control_permissons_MOD.js
> +        if (permissions.disallow?.has?.(perms) !== true) {
so does this

2021-06-29 23:38 UTC, tlfn commented on actions/control_permissons_MOD.js
> +        if (permissions.inherit?.includes?.(perms) === true) permissions.inherit.splice(permissions.inherit.indexOf(perms), 1)
so does this

2021-06-29 23:38 UTC, tlfn commented on actions/control_permissons_MOD.js
> +        if (permissions.disallow?.has?.(perms) === true) permissions.disallow.remove(perms)
so does this

2021-06-29 23:38 UTC, tlfn commented on actions/control_permissons_MOD.js
> +        if (!permissions.allow?.has?.(perms) !== true) {
so does this

2021-06-29 23:38 UTC, tlfn commented on actions/check_if_user_reacted_MOD.js
> +      result = reaction?.users?.cache?.has?.(member.id) === true
so does this

2021-06-29 23:39 UTC, tlfn commented on actions/check_if_user_reacted_MOD.js
> +      result = member.every((user) => reaction?.users?.cache?.has?.(user.id) === true)
so does this

2021-06-29 23:39 UTC, tlfn commented on actions/check_if_member_has_role_MOD.js
> +        result = member?.roles?.cache?.has?.(role.id) === true
so does this

2021-06-29 23:39 UTC, tlfn commented on actions/check_if_member_has_role_MOD.js
> +        result = member.every((mem) => mem?.roles?.cache?.has?.(role.id) === true)
so does this

2021-06-30 02:03 UTC, Fisheiyy commented
just woke up to 40 emails from github about commits maybe i should unsubscribe

2021-07-04 10:44 UTC, almeidx requested changes

2021-07-04 10:44 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        result = result?.[0]?.state
```suggestion
        result = user.presence.activities.find((s) => s.type === 'CUSTOM_STATUS')?.[0]?.state
```

2021-07-04 10:44 UTC, almeidx commented on actions/store_user_info_MOD.js
> +        result = result?.[0]?.name
```suggestion
        result = user.presence.activities.find((s) => s.type !== 'CUSTOM_STATUS')?.[0]?.name
```

2021-07-04 17:58 UTC, almeidx requested changes

2021-07-04 17:58 UTC, almeidx commented on actions/check_if_member_has_role_MOD.js
> +        result = member.every((mem) => mem?.roles?.cache.has(role.id))
```suggestion
        result = member.every((mem) => mem?.roles.cache.has(role.id))
```

2021-07-04 17:58 UTC, almeidx commented on actions/check_if_member_has_role_MOD.js
> +        result = !!member?.roles?.cache.has(role.id)
```suggestion
        result = !!member?.roles.cache.has(role.id)
```

2021-07-04 17:58 UTC, almeidx commented on actions/check_if_user_reacted_MOD.js
> +      result = member.every((user) => reaction?.users?.cache.has(user.id))
```suggestion
      result = member.every((user) => reaction?.users.cache.has(user.id))
```

2021-07-04 17:58 UTC, almeidx commented on actions/check_if_user_reacted_MOD.js
> +      result = !!reaction?.users?.cache.has(member.id)
```suggestion
      result = !!reaction?.users.cache.has(member.id)
```

2021-07-05 10:54 UTC, almeidx approved these changes

2021-08-23 09:22 UTC, closed without merging