Fix/Refactor Clone Channel action
dbm-network/mods pull request #741
Opened 2021-07-13 00:19 UTC by tlfn

**Please describe the changes this PR makes and why it should be merged:**
Discord.js `GuildChannel#clone` doesn't accept position.
Delete some duplicates

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-07-13 13:44 UTC, almeidx requested changes

2021-07-13 13:44 UTC, almeidx commented on actions/clone_channel_MOD.js
> +      .catch(this.displayError.bind(this, data, cache));
This doesn't call the next action

2021-07-13 13:50 UTC, tlfn commented on actions/clone_channel_MOD.js
> +      .catch(this.displayError.bind(this, data, cache));
It didn't, should it?

2021-07-13 13:52 UTC, almeidx commented on actions/clone_channel_MOD.js
> +      .catch(this.displayError.bind(this, data, cache));
Yes

2021-07-18 02:42 UTC, tlfn commented
@almeidx Bump

2021-07-18 08:56 UTC, almeidx approved these changes

2021-07-18 08:57 UTC, merged