Parse from stored json fix
dbm-network/mods pull request #799
Opened 2021-11-20 22:21 UTC by guitaarsfreack

2021-12-15 10:45 UTC, T0kyoofr approved these changes
Work fine on DBM V2

2022-01-24 00:46 UTC, almeidx requested changes

2022-01-24 00:46 UTC, almeidx commented on actions/parse_from_stored_json_MOD.js
> +        } else if (outValue.success === null || !outValue) {
```suggestion
        } else if (!outValue || outValue.success === null) {
```

2022-03-17 20:06 UTC, almeidx approved these changes

2022-03-17 20:07 UTC, merged