removed chalk as it will no longer work with this project.
dbm-network/mods pull request #839
Opened 2022-01-10 06:25 UTC by DetroitWhiskey136

also edited the moddep file to show a proper error when a module fails to load.

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-01-10 10:07 UTC, almeidx requested changes
Why was the colour support removed from Send Message to Console?

2022-01-10 10:07 UTC, almeidx commented on actions/aaa_dbmmods_dependencies_MOD.js
> +        console.error(error);
Or something similar 
```suggestion
        console.error(`Failed to install ${moduleName}. Error: ${error.message}`);
```

2022-01-10 21:52 UTC, DetroitWhiskey136 commented
chalk uses ESM now and i really couldn't be bothered to figure out how to use imports in the project

2022-01-10 21:53 UTC, DetroitWhiskey136 commented
For more info see [Chalk](https://www.npmjs.com/package/chalk)

2022-01-10 22:56 UTC, generalwrex commented
You don't need that module if you look at my other stuff I implemented the
coloring without any modules

On Mon, Jan 10, 2022, 1:53 PM Detroit Whiskey ***@***.***>
wrote:

> For more info see Chalk <https://www.npmjs.com/package/chalk>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dbm-network/mods/pull/839#issuecomment-1009379758>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANGUQZQLAUSKHNVT46PUB3UVNIPJANCNFSM5LS3ZJOA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-01-11 00:15 UTC, almeidx commented
> chalk uses ESM now and i really couldn't be bothered to figure out how to use imports in the project

Replace `require('chalk')` with `await import('chalk')`

2022-01-15 12:38 UTC, almeidx commented on actions/aaa_dbmmods_dependencies_MOD.js
> +  section: '#DBM Mods',
This should be updated in docs file

2022-01-15 12:39 UTC, almeidx commented on actions/mod_info_MOD.js
> +  section: '#DBM Mods',
This should be updated in docs file

2022-01-15 12:39 UTC, almeidx commented on actions/mod_info_MOD.js
> +  section: '#DBM Mods',
Also seems like there are some links pointing to the old repository URL. Should probably update those

2022-01-15 21:43 UTC, almeidx approved these changes

2022-01-15 21:44 UTC, merged