Upgraded Run Script Too
dbm-network/mods pull request #845
Opened 2022-01-27 19:40 UTC by KailHet

Changes:
1. Option to Hide/Show code field
2. New function to save variables from code (also have docs for it)
3. Updated style of the mod

Mod by Jek'a

2022-01-27 22:16 UTC, DetroitWhiskey136 requested changes
1) why did you remove the meta field?
2) you have a bunch of linting/prettier errors.
3) under fields try to use human readable variable names.

2023-02-05 21:16 UTC, DetroitWhiskey136 reviewed
For the linting errors regarding the unexpected functions, you can use an inline comment to ignore them. You can also place an underscore at the beginning of function arguments to signify that the argument isn't going to be used,
EXAMPLE:
`// eslint-disable-next-line func-names` ~ ignoring unnamed functions.
`glob.onDTLChanged = function (_event) {` ~ ignoring the fact event is never used.

2023-02-05 21:21 UTC, DetroitWhiskey136 requested changes

2023-02-05 21:21 UTC, DetroitWhiskey136 commented on actions/run_script_too_MOD.js
> +    glob.onSVarChanged = function (event) {
```suggestion
    // eslint-disable-next-line func-names
    glob.onSVarChanged = function (event) {
```

2023-02-05 21:21 UTC, DetroitWhiskey136 commented on actions/run_script_too_MOD.js
> +    glob.onShowCodeTypeChanged = function (event) {
```suggestion
    // eslint-disable-next-line func-names
    glob.onShowCodeTypeChanged = function (event) {
```

2023-02-05 21:21 UTC, DetroitWhiskey136 commented on actions/run_script_too_MOD.js
> +    glob.onDTLChanged = function (event) {
```suggestion
     // eslint-disable-next-line func-names
    glob.onDTLChanged = function (_event) {
```

2023-04-25 02:13 UTC, OneAndonlyFinbar commented
Closing because OP seems to have gone inactive. Feel free to reopen later.

2023-04-25 02:13 UTC, closed without merging