Added missing- , sorted and re-arranged permissions
dbm-network/mods pull request #861
Opened 2022-03-16 22:31 UTC by EliteArtz

**Please describe the changes this PR makes and why it should be merged:**
Added missing- , sorted and re-arranged options/permissions
**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [x] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

2022-03-16 22:37 UTC, almeidx requested changes
Please do not change the `permission` field values as to not make backwards-incompatible changes. Note that the HTML tags can be arranged as you like, what matters is the `value` attribute

2022-03-16 22:48 UTC, EliteArtz commented
> Please do not change the `permission` field values as to not make backwards-incompatible changes. Note that the HTML tags can be arranged as you like, what matters is the `value` attribute

I was aware of that, that's why I changed the cases in the switch to correspond to the right option.

2022-03-16 22:50 UTC, EliteArtz commented
I will commit one more to adjust the rest.

2022-03-16 22:54 UTC, almeidx commented
Adjusting the switch statement will not change the fact that it will be backwards-incompatible. Let's say, hypothetically, you were using this action and were setting the "Manage Guild" permission (value is "1"). After this change, as it is, the permission will now be changed to "View Channels"

2022-03-16 23:14 UTC, EliteArtz commented
The way how it works is through the values set in the `permission` select field, the saved variable `info` gets the current selected value, which then corresponds to the switch, which is using this `info` variable to define which bigint permission is about to used.

It will be saved to `result` and then it does the api request to Discord via the `setPermissions` Promise function.

The mod changes has been tested by me with good results.

2022-03-17 19:56 UTC, TheMonDon commented
That is not what alm meant, what alm is trying to say is you can't change the field value as it breaks existing commands and we try our best to not break it for backward comparability.

2022-03-17 21:28 UTC, EliteArtz commented
I see now..
Alright I am rearranging the values. The next commit should be hopefully final.

2022-03-17 22:27 UTC, almeidx reviewed
We should be using the [`Permissions.FLAGS`](https://discord.js.org/#/docs/discord.js/stable/class/Permissions?scrollTo=s-FLAGS) object instead of hardcoding the permission values, but its not a blocker

2022-03-17 22:27 UTC, almeidx commented on actions/set_role_perms_MOD.js
> +      if (Array.isArray(role))
This will never happen due to the if statement before this one (arrays don't have an `id` property)

2022-03-17 22:35 UTC, EliteArtz commented
> We should be using the [`Permissions.FLAGS`](https://discord.js.org/#/docs/discord.js/stable/class/Permissions?scrollTo=s-FLAGS) object instead of hardcoding the permission values, but its not a blocker

It would probably be better, yeah let's try to do that.
Either way, the Array if was not coded by me, but I'll be sure handle it.

2022-03-18 10:31 UTC, almeidx approved these changes

2022-03-18 10:35 UTC, merged