fixed a lot of the issues with voice channel perms
dbm-network/mods pull request #878
Opened 2022-06-14 23:02 UTC by DetroitWhiskey136

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-06-21 21:05 UTC, almeidx commented on actions/set_voice_channel_permissions_MOD.js
> +    console.log(data);
```suggestion
```

2022-06-21 21:06 UTC, almeidx commented on actions/set_voice_channel_permissions_MOD.js
>      this.callNextAction(cache);
```suggestion
    channel.permissionOverwrites
      // providing the server id is the same as providing the everyone role id;
      .edit(server.id, options, { type: 0 })
      .then(() => this.callNextAction(cache))
      .catch((err) => this.displayError(data, cache, err));
```

2022-06-22 20:53 UTC, almeidx requested changes

2022-06-22 20:53 UTC, almeidx commented on actions/set_role_voice_channel_perms_MOD.js
> +        .catch((err) => this.displayError.bind(data, cache, err));
```suggestion
        .catch((err) => this.displayError(data, cache, err));
```

2022-06-22 20:53 UTC, almeidx commented on actions/set_voice_channel_permissions_MOD.js
> +      .catch((err) => this.displayError.bind(data, cache, err));
```suggestion
      .catch((err) => this.displayError(data, cache, err));
```

2022-06-22 20:56 UTC, DetroitWhiskey136 commented
i'm so good at my job :)

2022-06-22 21:06 UTC, DetroitWhiskey136 commented on actions/set_voice_channel_permissions_MOD.js
> +    options[data.permission] = data.state === '0' ? true : data.state === '1' ? false : null;
idk why my changes didn't take... how strange

2022-06-22 21:07 UTC, DetroitWhiskey136 commented on actions/set_voice_channel_permissions_MOD.js
> +    options[data.permission] = data.state === '0' ? true : data.state === '1' ? false : null;
that array also wasn't supposed to be there

2022-06-22 21:11 UTC, DetroitWhiskey136 commented
would help if i was on the right branch lol

2022-06-22 21:18 UTC, DetroitWhiskey136 commented
ok that should have done the right thing this time.

2022-06-22 21:55 UTC, almeidx approved these changes

2022-06-22 21:56 UTC, merged