Fix send embed to webhook action
dbm-network/mods pull request #900
Opened 2022-08-14 21:44 UTC by ForceBlood

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [x] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-08-14 21:45 UTC, ForceBlood commented
Fixes #886

2022-08-14 21:49 UTC, OneAndonlyFinbar commented
`<WebhookClient>#send` Returns a promise

2022-08-15 14:49 UTC, almeidx commented on actions/send_embed_to_webhook_MOD.js
>      this.callNextAction(cache);
```suggestion
    webhook.send({ embeds: [embed2] })
      .then(() => this.callNextAction(cache))
      .catch((err) => this.displayError(data, cache, err));
```

2022-08-15 14:49 UTC, almeidx requested changes
https://github.com/dbm-network/mods/pull/900#discussion_r945828063

2022-08-15 14:59 UTC, almeidx approved these changes

2022-08-15 15:01 UTC, merged