Update mods to work with d.js v13
dbm-network/mods pull request #918
Opened 2022-12-08 22:14 UTC by TheMonDon

**Please describe the changes this PR makes and why it should be merged:**
I have fixed these two files and have confirmed them to be working inside of DBM.

**Status**

- [X] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [X] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-12-11 23:27 UTC, almeidx requested changes
Do not rename fields

2022-12-17 22:48 UTC, TheMonDon commented
@almeidx can you review this and accept it?

2022-12-17 23:11 UTC, almeidx requested changes

2022-12-17 23:11 UTC, almeidx commented on actions/set_role_voice_channel_perms_MOD.js
> +    const role = await this.getRoleFromData(data.storage2, data.varName2, cache);
Use the corresponding HTML elements
The first parameters should be `data.vchannel` and `data.role`

2022-12-17 23:11 UTC, almeidx commented on actions/set_slowmode_MOD.js
> +    return `${presets.getChannelText(data.channel, data.varName)} : ${data.amount} seconds`;
This field does not exist

2022-12-17 23:11 UTC, almeidx commented on actions/store_audit_log_list_MOD.js
> +        mem = await this.getMemberFromData(data.member - 1, data.varName, cache);
Use the corresponding HTML element

2022-12-17 23:11 UTC, almeidx commented on actions/store_channel_permissions_MOD.js
> +  <member-input dropdownLabel="Source Member" selectId="member" variableContainerId="memberVarNameContainer" variableInputId="memberVarName"></member-input>
The variableContainerId and variableInputId dont match the old ones

2022-12-17 23:11 UTC, almeidx commented on actions/store_channel_permissions_MOD.js
> +  <role-input dropdownLabel="Source Role" selectId="role" variableContainerId="roleVarNameContainer" variableInputId="varName2"></role-input>
The variableContainerId doesnt match the old ones

2022-12-17 23:11 UTC, almeidx commented on actions/store_message_params_MOD.js
> +        result = [...msg.mentions.users.values()].length > 0 ? [...msg.mentions.users.values()][ParamN - 1] : undefined;
```suggestion
        result = msg.mentions.users.at(ParamN - 1);
```

2022-12-17 23:11 UTC, almeidx commented on actions/store_message_params_MOD.js
> +          [...msg.mentions.members.values()].length > 0 ? [...msg.mentions.members.values()][ParamN - 1] : undefined;
```suggestion
        result = msg.mentions.members.at(ParamN - 1);
```

2022-12-17 23:11 UTC, almeidx commented on actions/store_message_params_MOD.js
> +        result = [...msg.mentions.roles.values()].length > 0 ? [...msg.mentions.roles.values()][ParamN - 1] : undefined;
```suggestion
        result = msg.mentions.roles.at(ParamN - 1);
```

2022-12-17 23:11 UTC, almeidx commented on actions/store_message_params_MOD.js
> +          [...msg.mentions.channels.values()].length > 0 ? [...msg.mentions.channels.values()][ParamN - 1] : undefined;
```suggestion
        result = msg.mentions.channels.at(ParamN - 1);
```

2022-12-17 23:11 UTC, almeidx commented on actions/typing_MOD.js
> +    const channel = await this.getChannelFromData(data.storage, data.varName, cache);
Use the corresponding HTML element

2022-12-17 23:11 UTC, almeidx commented on actions/weather_MOD.js
>    html(isEvent, data) {
```suggestion
  html() {
```

2022-12-17 23:49 UTC, TheMonDon commented on actions/parse_from_stored_json_MOD.js
> +        if (data.debugMode) console.log(outData);
You're right.

2022-12-18 00:18 UTC, TheMonDon commented on actions/store_audit_log_list_MOD.js
> +        mem = await this.getMemberFromData(data.member - 1, data.varName, cache);
Decided to revert this change,

2022-12-18 01:29 UTC, almeidx requested changes

2022-12-18 01:29 UTC, almeidx commented on actions/await_reaction_call_action_MOD.js
> +    <message-input dropdownLabel="Source Message" selectId="message" variableContainerId="varNameContainer" variableInputId="varName"></message-input>
```suggestion
    <message-input dropdownLabel="Source Message" selectId="storage" variableContainerId="varNameContainer" variableInputId="varName"></message-input>
```

2022-12-18 01:29 UTC, almeidx commented on actions/await_reaction_call_action_MOD.js
> +    const msg = await this.getMessageFromData(data.message, data.varName, cache);
```suggestion
    const msg = await this.getMessageFromData(data.storage, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/check_dbl_voted_MOD.js
> +    const member = await this.getMemberFromData(data.type, data.varName, cache);
```suggestion
    const member = await this.getMemberFromData(data.member, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/check_if_member_MOD.js
> +    const member = await this.getMemberFromData(data.type, data.varName, cache);
```suggestion
    const member = await this.getMemberFromData(data.member, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/check_if_user_reacted_MOD.js
> +    const member = await this.getMemberFromData(data.type, data.varName, cache);
```suggestion
    const member = await this.getMemberFromData(data.member, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/check_role_permissions_MOD.js
> +    const role = await this.getRoleFromData(data.storage, data.varName, cache);
```suggestion
    const role = await this.getRoleFromData(data.role, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/clone_channel_MOD.js
> +    return `Clone Channel: ${presets.getChannelText(data.channel, data.varName)}`;
```suggestion
    return `Clone Channel: ${presets.getChannelText(data.storage, data.varName)}`;
```

2022-12-18 01:29 UTC, almeidx commented on actions/control_server_prefix_MOD.js
> +    const server = await this.getServerFromData(data.type, data.varName, cache);
```suggestion
    const server = await this.getServerFromData(data.server, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/delete_member_data_MOD.js
> +    const member = await this.getMemberFromData(data.type, data.varName, data.cache);
```suggestion
    const member = await this.getMemberFromData(data.member, data.varName, data.cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/delete_server_data_MOD.js
> +    const server = await this.getServerFromData(data.type, data.varName, cache);
```suggestion
    const server = await this.getServerFromData(data.server, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/leave_server_MOD.js
> +    const server = await this.getServerFromData(data.type, data.varName, cache);
```suggestion
    const server = await this.getServerFromData(data.server, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/remove_reaction_MOD.js
> +<member-input dropdownLabel="Source Member" selectId="member" variableContainerId="varNameContainer" variableInputId="varName"></member-input>
```suggestion
<member-input dropdownLabel="Source Member" selectId="member" variableContainerId="varNameContainer2" variableInputId="varName2"></member-input>
```

2022-12-18 01:29 UTC, almeidx commented on actions/set_afk_channel_MOD.js
> +    const server = await this.getServerFromData(data.type, data.varName, cache);
```suggestion
    const server = await this.getServerFromData(data.server, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/set_afk_channel_MOD.js
> +    const channel = await this.getVoiceChannelFromData(data.afkchannel, data.varName2, cache);
```suggestion
    const channel = await this.getVoiceChannelFromData(data.afkchannel, data.varNameChannel, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/set_member_voice_channel_perms_MOD.js
> +    const channel = await this.getVoiceChannelFromData(data.storage, data.varName, cache);
```suggestion
    const channel = await this.getVoiceChannelFromData(data.vchannel, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/set_member_voice_channel_perms_MOD.js
> +    const member = await this.getMemberFromData(data.storage2, data.varName2, cache);
```suggestion
    const member = await this.getMemberFromData(data.member, data.varName2, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/set_permissions_MOD.js
> +    let permissions = this.getVariableFromData(data.storage2, data.varName2, cache);
I don't believe this function exists

2022-12-18 01:29 UTC, almeidx commented on actions/set_server_owner_MOD.js
> +    const server = await this.getServerFromData(data.type, data.varName, cache);
```suggestion
    const server = await this.getServerFromData(data.server, data.varName, cache);
```

2022-12-18 01:29 UTC, almeidx commented on actions/store_category_info_MOD.js
> +          .array(); // Category Text Channel List
```suggestion
        result = [...targetCategory.children
          .filter((c) => ['GUILD_TEXT', 'GUILD_NEWS', 'GUILD_STORE'].includes(c.type))
          .values()]; // Category Text Channel List
```

2022-12-18 01:29 UTC, almeidx commented on actions/store_category_info_MOD.js
> +        result = targetCategory.children.filter((c) => c.type === 'GUILD_VOICE').array(); // Category Voice Channel List
```suggestion
        result = [...targetCategory.children.filter((c) => c.type === 'GUILD_VOICE').values()]; // Category Voice Channel List
```

2022-12-18 01:29 UTC, almeidx commented on actions/store_channel_permissions_MOD.js
> +    return `${presets.getChannelText(data.channel, data.channelVarNameContainer)} - ${
```suggestion
    return `${presets.getChannelText(data.storage, data.varName)} - ${
```

2022-12-18 01:29 UTC, almeidx commented on actions/store_channel_permissions_MOD.js
> +  <member-input dropdownLabel="Source Member" selectId="member" variableContainerId="arNameContainer3" variableInputId="memberVarName"></member-input>
```suggestion
  <member-input dropdownLabel="Source Member" selectId="member" variableContainerId="varNameContainer3" variableInputId="varName3"></member-input>
```

2022-12-18 01:29 UTC, almeidx commented on actions/store_channel_permissions_MOD.js
> +  <role-input dropdownLabel="Source Role" selectId="role" variableContainerId="arNameContainer2" variableInputId="varName2"></role-input>
```suggestion
  <role-input dropdownLabel="Source Role" selectId="role" variableContainerId="varNameContainer2" variableInputId="varName2"></role-input>
```

2022-12-18 01:58 UTC, almeidx approved these changes

2022-12-18 02:02 UTC, merged