Update global_data_MOD.js
dbm-network/mods pull request #955
Opened 2023-05-20 07:36 UTC by Phyrok

**Please describe the changes this PR makes and why it should be merged:**
Outdated looks updated to look more appealing with the rest of the actions.

Removal of unnecessary code in **Check_Global_Data.js** as it DBM has a build in conditional input. 

| **Check_Global_Data.js** | **Control_Global_Data.js** | **Delete_Global_Data.js** | **Store_Global_Data.js** |
| :--- | :--- | :--- | :--- | 
| <details> <summary>Before</summary> ![image](https://github.com/dbm-network/mods/assets/69722956/0d2d1fe3-387d-4688-ab3f-64c19d0d7593) </details> | <details> <summary>Before</summary> ![image](https://github.com/dbm-network/mods/assets/69722956/c8a50c81-410a-48e7-a05b-26222ed5d6fd) </details> | <details> <summary>Before</summary> ![image](https://github.com/dbm-network/mods/assets/69722956/590db683-cabe-4f59-9885-f5667b904628) </details> | <details> <summary>Before</summary> ![image](https://github.com/dbm-network/mods/assets/69722956/d02e8db8-eb79-4c4c-8025-e311d896658b) </details>
|<details> <summary>After</summary> ![image](https://github.com/dbm-network/mods/assets/69722956/8d81a9fd-0084-4008-9ca2-ae6b939f235f) </details> | <details> <summary>After</summary> ![image](https://github.com/dbm-network/mods/assets/69722956/43757084-ab80-42e1-b927-5e7f0ce656ac) </details> | <details> <summary>After</summary> ![image](https://github.com/dbm-network/mods/assets/69722956/7a5de60c-cc9e-4438-9993-8a607be272c2) </details> | <details> <summary>After</summary> ![image](https://github.com/dbm-network/mods/assets/69722956/4dc19dca-b5e7-43f1-ba7f-19fe13ac3bec) </details>

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-05-20 07:41 UTC, Phyrok commented
I think I closed the previous by removing the repo of my GitHub Desktop.
Sorry for the trouble I am causing.

2023-05-20 11:23 UTC, TheMonDon requested changes
My bad I told you to remove document not what i meant

2023-05-20 11:23 UTC, TheMonDon commented on actions/check_global_data_MOD.js
> +        getElementById('directValue').style.display = null;
```suggestion
        document.getElementById('directValue').style.display = null;
```

2023-05-20 11:23 UTC, TheMonDon commented on actions/check_global_data_MOD.js
> +        getElementById('directValue').style.display = 'none';
```suggestion
        document.getElementById('directValue').style.display = 'none';
```

2023-05-20 11:23 UTC, TheMonDon commented on actions/check_global_data_MOD.js
> +    const { glob } = this;
```suggestion
    const { glob, document } = this;
```

2023-05-20 11:25 UTC, TheMonDon requested changes

2023-05-20 11:25 UTC, TheMonDon commented on actions/check_global_data_MOD.js
> +    glob.onComparisonChanged(getElementById('comparison'));
```suggestion
    document.glob.onComparisonChanged(getElementById('comparison'));
```

2023-05-20 11:27 UTC, TheMonDon requested changes

2023-05-20 11:27 UTC, TheMonDon commented on actions/check_global_data_MOD.js
> +    document.glob.onComparisonChanged(getElementById('comparison'));
```suggestion
    glob.onComparisonChanged(document.getElementById('comparison'));
```

2023-05-21 02:56 UTC, TheMonDon requested changes

2023-05-21 02:56 UTC, TheMonDon commented on actions/check_global_data_MOD.js
>    subtitle(data) {
```suggestion

  subtitle(data) {
```

2023-05-21 02:56 UTC, TheMonDon commented on actions/control_global_data_MOD.js
>    subtitle(data) {
```suggestion

  subtitle(data) {
```

2023-05-21 02:56 UTC, TheMonDon commented on actions/delete_global_data_MOD.js
>      <input id="dataName" class="round" placeholder="Leave it blank to delete all data" type="text">
```suggestion
    <input id="dataName" class="round" placeholder="Leave blank to delete all data" type="text">
```

2023-05-21 02:56 UTC, TheMonDon commented on actions/delete_global_data_MOD.js
>    subtitle(data) {
```suggestion

  subtitle(data) {
```

2023-05-21 02:56 UTC, TheMonDon commented on actions/store_global_data_MOD.js
>    subtitle(data, presets) {
```suggestion

  subtitle(data, presets) {
```

2023-05-21 02:56 UTC, TheMonDon commented on actions/store_global_data_MOD.js
>    variableStorage(data, varType) {
```suggestion

  variableStorage(data, varType) {
```

2023-05-21 03:04 UTC, TheMonDon commented on actions/store_global_data_MOD.js
>    variableStorage(data, varType) {
I think this is all the changes I'd like, i'll take a look after these are added and then approve the PR.

2023-05-21 03:51 UTC, TheMonDon approved these changes

2023-05-21 03:53 UTC, merged