Update mods to dbminputlabel and preset variables
dbm-network/mods pull request #961
Opened 2023-05-24 21:54 UTC by TheMonDon

**Please describe the changes this PR makes and why it should be merged:**
Updating all of the mods to use DBMs new html interfaces for ease of use.
5/24/23 4:54PM: 40/188 actions done

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [X] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-05-24 22:21 UTC, OneAndonlyFinbar commented
Damnit

2023-05-30 22:51 UTC, OneAndonlyFinbar requested changes

2023-05-30 22:51 UTC, OneAndonlyFinbar commented on actions/store_date_info_MOD.js
> -module.exports = {
feel like this shouldnt be removed as a whole

2023-05-30 22:54 UTC, almeidx requested changes

2023-05-30 22:54 UTC, almeidx commented on events/message_reaction_added_EVT.js
> +  name: 'Message Reaction Added',
Changing the `name` property will break existing events that users might be using. Should probably revert all the changes in the `events` folder

2023-05-31 15:40 UTC, OneAndonlyFinbar approved these changes

2023-05-31 15:45 UTC, merged