Stage Voice Channel Create
dbm-network/mods pull request #969
Opened 2023-06-01 16:44 UTC by dbmIsaac

Created Stage voice channel action

**Please describe the changes this PR makes and why it should be merged:**
Created a action to create stage voice channels. 
**Status**

- [X] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [X] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-06-01 18:47 UTC, DetroitWhiskey136 requested changes
You'll have to sort out your linting errors before proceeding :)

2023-06-02 02:04 UTC, TheMonDon requested changes
Commit all of these changes and then I will see if there are any other changes needed.

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  // ---------------------------------------------------------------------
```suggestion
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  subtitle(data, presets) {
```suggestion
  subtitle(data) {
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  // ---------------------------------------------------------------------
```suggestion
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  // ---------------------------------------------------------------------
```suggestion
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  meta: { version: '2.1.7', preciseCheck: true, author: null, authorUrl: null, downloadUrl: null },
```suggestion
  meta: { version: '2.1.7', preciseCheck: false, author: 'DBM Mods', authorUrl: 'https://github.com/dbm-network/mods', downloadUrl: 'https://github.com/dbm-network/mods/blob/master/actions/create_stage_voice_channel.js' },
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  // ---------------------------------------------------------------------
```suggestion
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  // ---------------------------------------------------------------------
```suggestion
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  html(isEvent, data) {
```suggestion
  html() {
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  // ---------------------------------------------------------------------
```suggestion
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  // ---------------------------------------------------------------------
```suggestion
```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +    /** @type {import('discord.js').GuildChannelCreateOptions} */
```suggestion

```

2023-06-02 02:04 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  // ---------------------------------------------------------------------
```suggestion
```

2023-06-06 22:59 UTC, TheMonDon requested changes

2023-06-06 22:59 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +  fields: ['channelName', 'bitrate', 'userLimit', 'varName', 'categoryID', 'reason'],
```suggestion
  fields: ['channelName', 'categoryID', 'bitrate', 'userLimit', 'reason', 'storage', 'varName'],
```

2023-06-06 22:59 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +
```suggestion
```

2023-06-06 22:59 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +      })
```suggestion
      .create(name, channelData)
```

2023-06-06 22:59 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +    if (data.bitrate) {
```suggestion

    if (data.reason) {
      channelData.reason = this.evalMessage(data.reason, cache);
    }
    if (data.bitrate) {
```

2023-06-06 22:59 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +    const reason = this.evalMessage(data.reason, cache);
```suggestion
```

2023-06-06 22:59 UTC, TheMonDon commented on actions/create_stage_voice_channel.js
> +    const channelData = { reason };
```suggestion
    const channelData = { type: 'GUILD_STAGE_VOICE' };
```

2023-06-10 18:32 UTC, TheMonDon commented
Closed on request of author

2023-06-10 18:32 UTC, closed without merging