Create create_private_thread_MOD.js
dbm-network/mods pull request #989
Opened 2023-07-09 17:12 UTC by Phyrok

**Please describe the changes this PR makes and why it should be merged:**
New Mod Private Thread

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-07-09 17:35 UTC, TheMonDon commented
DBM 2.2.0 already has private threads there's no reason to create a mod

2023-10-20 19:34 UTC, DetroitWhiskey136 commented
you could probably move all of this into a single action... using tabs or something.

2023-11-16 16:10 UTC, Phyrok reviewed
Updated ESLint

2023-11-16 16:41 UTC, TheMonDon approved these changes

2023-11-16 16:42 UTC, TheMonDon requested changes

2023-11-16 16:42 UTC, TheMonDon commented on actions/remove_member_from_thread_MOD.js
> +  name: 'Remove Member to Thread',
```suggestion
  name: 'Remove Member from Thread',
```

2023-11-16 16:42 UTC, TheMonDon commented on docs/mods.json
> +    "description": "Remove Member From Private Thread",
```suggestion
    "description": "Remove Member From Thread",
```

2023-11-16 16:42 UTC, TheMonDon commented on docs/mods.json
> +    "description": "Add Member To Private Thread",
```suggestion
    "description": "Add Member To Thread",
```

2023-11-18 00:39 UTC, OneAndonlyFinbar approved these changes

2023-11-18 01:24 UTC, merged